# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Responsive Website Templates
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A Bootstrap based jekyll themes.

baseurl: "/FrontEnd" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#footer
built-by: Mr.Wang

copyright:
   name: Mr.Wang
   link: 'http://www.wordpress.com'

sass:
  style: :compressed